<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.xpath: //select[@aria-label="Service Location Type"] (tried for 20 second(s) with 500 milliseconds interval)]]>
    </line>
    <line>
      <![CDATA[org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : Fail to load Public Key}
  (Session info: chrome=91.0.4472.101): Fail to load Public Key
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-Q49L3C5V', ip: '10.10.2.142', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_241'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 91.0.4472.101, chrome: {chromedriverVersion: 91.0.4472.19 (1bf021f248676..., userDataDir: C:\Users\Jonathan\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:49435}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 423d7229bbab950d4a671c68770a09e9]]>
    </line>
  </reporter-output>
  <suite name="Command line suite" duration-ms="140955" started-at="2021-06-10T15:17:29 EDT" finished-at="2021-06-10T15:19:50 EDT">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="140955" started-at="2021-06-10T15:17:29 EDT" finished-at="2021-06-10T15:19:50 EDT">
      <class name="ca.elecsoft.seeding.SeedQA3">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:ca.elecsoft.seeding.SeedQA3@167c1fc]" name="beforeMethod" is-config="true" duration-ms="1785" started-at="2021-06-10T15:17:30 EDT" finished-at="2021-06-10T15:17:31 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="seedOrder(ca.elecsoft.model.DataSeedModel)[pri:0, instance:ca.elecsoft.seeding.SeedQA3@167c1fc]" name="seedOrder" duration-ms="58243" started-at="2021-06-10T15:17:31 EDT" data-provider="workOrders" finished-at="2021-06-10T15:18:30 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[DataSeedModel{requestType='Residential', workOrderType='Provisioning', workOrderSubType='Install - Wireless / Installation - Sans fil', serviceLocationtype='Security', province='ON', bundle='Q-GOOD', includedChoice='NA', addtionalItem=[], promotions=[], postalCode='M4V1C7', paymentMethod='Debit'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [error] but found [error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [error] but found [error]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertNotEquals(Assert.java:1399)
at org.testng.Assert.assertNotEquals(Assert.java:1404)
at ca.elecsoft.seeding.SeedQA3.seedOrder(SeedQA3.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at ca.elecsoft.seeding.MainSeed.main(MainSeed.java:16)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.xpath: //select[@aria-label="Service Location Type"] (tried for 20 second(s) with 500 milliseconds interval)]]>
            </line>
          </reporter-output>
        </test-method> <!-- seedOrder -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:ca.elecsoft.seeding.SeedQA3@167c1fc]" name="afterMethod" is-config="true" duration-ms="816" started-at="2021-06-10T15:18:30 EDT" finished-at="2021-06-10T15:18:30 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:ca.elecsoft.seeding.SeedQA3@167c1fc]" name="beforeMethod" is-config="true" duration-ms="1598" started-at="2021-06-10T15:18:30 EDT" finished-at="2021-06-10T15:18:32 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="seedOrder(ca.elecsoft.model.DataSeedModel)[pri:0, instance:ca.elecsoft.seeding.SeedQA3@167c1fc]" name="seedOrder" duration-ms="76999" started-at="2021-06-10T15:18:32 EDT" data-provider="workOrders" finished-at="2021-06-10T15:19:49 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[DataSeedModel{requestType='Residential', workOrderType='Provisioning', workOrderSubType='Install - Wireless / Installation - Sans fil', serviceLocationtype='Security', province='ON', bundle='QGDAUTO', includedChoice='NA', addtionalItem=[], promotions=[], postalCode='M4V1C7', paymentMethod='Debit'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [error] but found [error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [error] but found [error]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertNotEquals(Assert.java:1399)
at org.testng.Assert.assertNotEquals(Assert.java:1404)
at ca.elecsoft.seeding.SeedQA3.seedOrder(SeedQA3.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at ca.elecsoft.seeding.MainSeed.main(MainSeed.java:16)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : Fail to load Public Key}
  (Session info: chrome=91.0.4472.101): Fail to load Public Key
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-Q49L3C5V', ip: '10.10.2.142', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_241'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 91.0.4472.101, chrome: {chromedriverVersion: 91.0.4472.19 (1bf021f248676..., userDataDir: C:\Users\Jonathan\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:49435}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 423d7229bbab950d4a671c68770a09e9]]>
            </line>
          </reporter-output>
        </test-method> <!-- seedOrder -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:ca.elecsoft.seeding.SeedQA3@167c1fc]" name="afterMethod" is-config="true" duration-ms="955" started-at="2021-06-10T15:19:49 EDT" finished-at="2021-06-10T15:19:50 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- ca.elecsoft.seeding.SeedQA3 -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
